# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25d4ca942accb9e0772e5516289d03259252e0ea1f4048b47a1006d310b8b4cd1ce479876494bc019b8e407f87e42c546af08a31f105bdbdc6a4707d17e7d548

test:
  secret_key_base: d6c3e977344d71fd4852561b329d7068bb46cf24563b4fb19421662eee0e14595316a01c6a1cb6dc26d27081dbc10631cd543206a8dd7790470af1b8125f582c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
